name: video_editing_app
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  get_cli: ^1.8.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  get: 4.6.4
  flutter_svg: ^1.1.5
  dropdown_button2: ^1.8.9

  roundcheckbox: ^2.0.5


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    -
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf


  uses-material-design: true

